export const DEF_ACTIONS = {
    ADD: 'ADD',
    VIEW: 'VIEW',
    VIEW_LIST: 'VIEW_LIST',
    EDIT: 'EDIT',
    DELETE: 'DELETE',
}

export const DEF_COMPONENTS = {
    COMPONENT: 'COMPONENT',
    ROLE: 'ROLE',
    PERMISSION: 'PERMISSION',
    ACTION: 'ACTION',
    PROVINCE: 'PROVINCE',
    DISTRICT: 'DISTRICT',
    DS_DIVISION: 'DSDIVISION',
    GN_DIVISION: 'GNDIVISION',
    SOIL: 'SOIL',
    ASC: 'ASC',
    ARPA: 'ARPA',
    AI: 'AI',
}