export const DEF_ACTIONS = {
    ADD: 'ADD',
    VIEW: 'VIEW',
    VIEW_LIST: 'VIEW_LIST',
    EDIT: 'EDIT',
    DELETE: 'DELETE',
}

export const DEF_COMPONENTS = {
    COMPONENT: 'COMPONENT',
    ROLE: 'ROLE',
    PERMISSION: 'PERMISSION',
    ACTION: 'ACTION',
    PROVINCES: 'PROVINCES',
    DISTRICTS: 'DISTRICTS'
}