# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: AgriClient prod CI/CD

on: [workflow_dispatch]

env:
  CI : false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: oneszeros/eagriservice
        tags: ${GITHUB_RUN_ID}, latest
        registry: docker.io
        dockerfile: Dockerfile
        buildArgs: |
          base_url=43.205.75.154
        username: oneszeros
        password: AstroBoy@2023
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 43.205.75.154
        username: ec2-user
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEogIBAAKCAQEAneX3QM2aDTf15nxEcJf4L/krONee4jx7fA6VAIArp0ulBP82
          NouJR5lDClSMN7VQDw1pa/ZcTUR0xX2a5o8cjiWDV+9HihRABX7C+PUV1sD4DyU9
          H8uzJR/RFTLIndt6WyGP/PjaXj84MwnEUuNMcLfOJmXUpsy/cc+cVbTDqHQbq4yG
          NCqaS9bloVNXCL56mhr3cb3frRaVHJgfFiLyLeEfL0AmUTlYHafWXRJF0ncWsmFK
          1y4tR/3y6jhpeWWEXR95dIDARHtSd3Cvy4eDbBhViJPB+154DNTyhLTnFkjmELqI
          +YBYM2qdYQHjzAwWGH7Te1w1kvb/7n80AxDQUQIDAQABAoIBAGBHLdl0xH9U5PqS
          QUUKVQoje4hgaX/3czA00AQLIxMSW9/NIihmMuHWgPtWjF0XkGZtPh/Xi3aNzEnz
          ibUWBEpkc072FwAJ0vPG1GnrP1LAPUE26qttkKGNYfb0DUG750KUF3Ef6D7Ze5Ib
          XXtRH3YHjYr6Qo0mgYGLHv9fhoI6vHEgq8d/0QZ9kXBw0xI1oqLrCp8JFQfZgC45
          2ENJr2f3HBHvOO422l0XOlcvbyDTTzKOTA4flLDztPTFUMbL6lRlsJnqf8xyx7XO
          8ZTJWThTWdDSzWNNRYMS1DkPO19ppzNjNnuuiBZK+Z2L0dH+QuvC/HrpgEsrbqUO
          pED8qZUCgYEA0/lEinTc9Au+tm84NeLPU1HHb/p4v55UK4/0Jn4c6KKP2obKw333
          AbNSUfsKmGSSvOVOrWhWIpDjtcFe7rZLpJsJMTmXYAlxyjNqPYWqNpSI6xhq9q49
          d5FCaLmbCTUaMolGtcyVGlIy5sADT+OkUpyyAApE7TJws4lA8ucGpisCgYEAvrF8
          cDY0sZgHejGPTAzzo4jW2Ou7J0puIaxMzfdAtSgvE+zp74xmqebksANis6kvdsBz
          AX7wUPm82wt7R1G5rVOAlmBEC5q8hze9fvclG5SAnCsvjSdT7SPZeQQgZFRsmdVZ
          iNTnRXWf1AsD2QapWEtMi7SMgL3Gks9PP4RKAXMCgYAEF26kQYc2Sre+q7zpBVy9
          Hfn8hlgoUrULNjcfOxXxw5mFPU7SoS7QYJa5MGBO+rn+XWq8XCQ1fJh4nKfpcala
          Hwf5ZEQwvV3t6jolv9u+O/W8m/cMleZn1WzzuolsjxLXYOD1h2JlZKrI23H0687z
          LUUeTRRxg6S7Qm33glAViwKBgHXxJHvqqtCkrQtAl9Z7tD0TJ37m3cxBVrhw7tf8
          8wKYpfV29IF6nwy6h/rtPSDNpVOXWAo2zr/mlo4MHeVQgLzZBpD7XVqoC66+JO/g
          QA083ga5FyIAjwH+yET27mnfZYQH1uawd5IYXBAz999FJXw8pk1KEBSYS7cFjYhF
          c9hNAoGAF1PVgwXEnERHCIBj7WPTdoBIk+bi0i0vICcua657PdZj0bQW4mgww8Cc
          GWmeSA8Fywidytl//hJYphaP4khv1PMNH7tyK5BzM9I1X5I1qJkAouH1XhyAYTzh
          dhcmGdAFeeDpUAX1IAlhzS6C7G53IvjDz8AbitqZJr4uJujndig=
          -----END RSA PRIVATE KEY-----
        script: |
          docker login
          docker pull oneszeros/eagriservice:latest
          docker stop agriclient
          docker rm agriclient
          docker run -d --name agriclient -p 80:80 oneszeros/eagriservice:latest
