# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: sgClient prod CI/CD

on: [workflow_dispatch]

env:
  CI : false

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install
    - run: yarn build
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: vijithakn/sgclient
        tags: ${GITHUB_RUN_ID}, latest
        registry: docker.io
        dockerfile: Dockerfile
        buildArgs: |
          base_url=http://3.6.216.178
        username: vijithakn
        password: 0nly4@vijitha
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 3.6.216.178
        username: ec2-user
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEogIBAAKCAQEAhTZ+apO4yyq6HX2IOc+0oewO9UJ/Ol+jZLpz7GGc7hZhWHu+
          fMAJ+PrFPphO0bkwn+u9QfNRiA50Y+YBZqvGJ3pPKDEXJL5S1ZDkV1ohKe1lMktC
          XfZpiM9G0qB0Re2qQ1ofxY9eIps0GQXI4vaBH6OVugATqu+6wA5nPbAIAwQD3ACy
          IHDTeCv4ozxjXnkmtytRJOJzH4UxcfI9TYzOJoGBRoWr3VQvGcFe4zM7Dg1nABRD
          tExkOn2jqiDWVW6w31xJ7t6JS/V3pShyXRqvuLj9Ewp2I8h/BFN2lNaz3MkeoXxi
          jUgvaox8f/1DyrXsn+dXqu0lWa0hsGa4QcA4/wIDAQABAoIBAGcJ05aUVKexkOwm
          oSw2YL2uXZOPr+FzAGt1XR1GE6CFZx6N+LV9xTj0n4TfQnguClJogad1kWbv508u
          JX9I9qiqjnfEIOam4GOZA0YdzPElUtUoKVmMs+zCh0F8IvPD9aLLHzAsyN9ztUR1
          mQEVMqNKYRHR5WSesZDEk06/zjKl1idO15GI+HBr/ltc3BeIlCx/TkWgETZiH8Ir
          TlX3XxkfBvRjdKcMLc0o46vOB99Ufh+zl3u5qsD3azed3hD8MUiWl3/m9KK1/eWb
          LFgSEz7Sk6z/AH3N1+5hG+ZW5hGtEe6VrBPv9e9TPXmMhnku8Ctz0Ah950PvcrZz
          Dk2bFoECgYEAxKY7z3EtdPtoXHNnUE3ZYiy01iwM2unSWY0SiiXhNFpbm1f0GULZ
          L2W5LPelIzXVyVzUsHReY3zAiIcG7OVCQoXa8rSam6ji74aoHxjANyD0xhIoj1Ax
          NGWghRWt86p1GYz8gszeGLyUhiPhB7/sCRdOSDcVQAmn6rAH8ZFkIbECgYEArWrz
          p7e5c2hwtraX49/wC7OX8EBAUb0BIR59e5js7G9WKBdcgDqGNK6lJermaTmpifD4
          jfsZ3Z6ZT1cCxh0JkuiQtnrvSSgejEMjsksrPvTcbCxR7PvMWWfPJt54ilbgB+4Z
          uiuy3HxZtUpNubh2+rtXaVzyTIcIWk1dhRhDga8CgYADJo6qwityRlzjrk2ncbfb
          5M945vfFwh1GpgX4BKdZCWGSWZRlmzaTldOjrswMhl5IfZ5CvXqNqYAEL/WicgHf
          wvlBDjez6r7IC6ZB6UmbGIITclMICMbhCgfKWhCRaNe7cxDQn6unRc4zX/vI/gAw
          HRl5+rfycLUqA2v9KNEr4QKBgBMH4aVOLDPWCkiC0ThYoucl1k6vPl+59h3EUtD1
          f0qTDUlpBuWrhn7Ri54VoSN7CHfy0dQC8lu3w+tJCSzkkuBkVT0xUIEevft2grxW
          M3C9PlNAqdzv5QUKt1j0oRXNYth78KbVlNNNcirK9Kyk6amqVXVildSAHRKL2u94
          MjBRAoGAHbmNXw1scy7fE23h3U+M+tL5Dst9Q3SD8YvNj+Sr2EJtDH4rUJkON7o9
          kUuBBtxxaXVAiboQFEqYeKvA7JnNuKmb2nHIbBs5HVjSwMfltm6tVC52rboZ1J9r
          iwyXzKvjUBi1eBuSlFWZqq7A0YpNJRLGKkxuRVQxfFdml47Q1C0=
          -----END RSA PRIVATE KEY-----
        script: |
          docker login
          docker pull vijithakn/sgclient:latest
          docker stop sgclient
          docker rm sgclient
          docker run -d --name sgclient -p 80:80 vijithakn/sgclient:latest
